version: '3'

services:
  mariadb:
    image: bitnami/mariadb:10.5
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=developer
      - MARIADB_PASSWORD=123
      - MARIADB_DATABASE=auth
      - MARIADB_SKIP_TEST_DB=yes
    ports: 
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb/data
    restart: always

volumes:
  mariadb_data:
