name: CI

on:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install depencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
      
    - name: Lint with wemake
      uses: wemake-services/wemake-python-styleguide@0.15.3

    - name: Type checking with mypy
      run: mypy  --config-file .github/setup.cfg .

  notify:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: If success
        if: ${{ needs.build.result == 'success'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ✅ User ${{github.actor}} in ${{ github.repository }} repository. Try to make ${{ github.event_name }}. Status - success.

      - name: If failure
        if: ${{ needs.build.result == 'failure'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ❌ User ${{github.actor}} in ${{ github.repository }} repository. Try to make ${{ github.event_name }}. Status - error.


